# docker-compose.yml
version: "3.9"
services:
    server:
        build: ./server
        ports: 
            - 5055:5000
        command: npm run dev
        volumes: 
            - ./server/src/:/app/src/
    mongodb:
        image: mongo
    client:
        build: ./client/my-app
        command: npm run start
        ports:
            - 8080:3000
        volumes:
            - '/client/my-app/node_modules'
        environment:
            - CHOKIDAR_USEPOLLING=true